name: Infra as Code Pipeline

on:
  pull_request:
    branches:
      - main
      - staging

  push:
    branches:
      - main
      - staging

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

##########################################################
# JOBS
##########################################################

jobs:

##########################################################
# TERRAFORM VALIDATION
##########################################################

  terraform-validation:

    name: Terraform Validate

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      ####################################################
      # Checkout Repository
      ####################################################

      - name: Checkout Repository

        uses: actions/checkout@v4

      ####################################################
      # Configure AWS Credentials
      ####################################################

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      ####################################################
      # Setup Terraform
      ####################################################

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

        with:
          terraform_wrapper: false

      ####################################################
      # Terraform Version
      ####################################################

      - name: Terraform Version

        run: terraform version

      ####################################################
      # Terraform Init
      ####################################################

      - name: Terraform Init

        run: terraform init

      ####################################################
      # Terraform Format Check
      ####################################################

      - name: Terraform Format

        run: terraform fmt -check -recursive

      ####################################################
      # Terraform Validate
      ####################################################

      - name: Terraform Validate

        run: terraform validate

      ####################################################
      # Upload Terraform Source
      ####################################################

      - name: Upload Terraform Source

        uses: actions/upload-artifact@v4

        with:
          name: terraform-source
          path: terraform

##########################################################
# TERRAFORM LINT
##########################################################

  terraform-lint:

    name: Terraform Lint

    needs: terraform-validation

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      ####################################################
      # Checkout
      ####################################################

      - name: Checkout Repository

        uses: actions/checkout@v4

      ####################################################
      # Install TFLint
      ####################################################

      - name: Install TFLint

        uses: terraform-linters/setup-tflint@v4

      ####################################################
      # Verify Version
      ####################################################

      - name: Check Version

        run: tflint --version

      ####################################################
      # Initialize Rules
      ####################################################

      - name: Initialize TFLint

        run: tflint --init

      ####################################################
      # Execute TFLint
      ####################################################

      - name: Run TFLint

        run: tflint

      ####################################################
      # Upload Lint Report
      ####################################################

      - name: Upload Lint Report

        uses: actions/upload-artifact@v4

        with:
          name: terraform-lint
          path: terraform

##########################################################
# PART B STARTS BELOW
####################################################################################################################
# DOCKER BUILD & PUSH
##########################################################

  docker-build:

    name: Build & Push Docker Image

    needs:
      - terraform-validation
      - terraform-lint

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    outputs:
      image-uri: ${{ steps.export-image.outputs.image }}

    steps:

      ####################################################
      # Checkout Repository
      ####################################################

      - name: Checkout Repository

        uses: actions/checkout@v4

      ####################################################
      # Configure AWS Credentials
      ####################################################

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      ####################################################
      # Login to Amazon ECR
      ####################################################

      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # Show Docker Version
      ####################################################

      - name: Docker Version

        run: docker version

      ####################################################
      # Build Docker Image
      ####################################################

      - name: Build Docker Image

        run: |

          docker build \
            -t $ECR_REPOSITORY:${{ github.sha }} \
            .

      ####################################################
      # Tag Docker Image
      ####################################################

      - name: Tag Docker Image

        run: |

          docker tag \
            $ECR_REPOSITORY:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      ####################################################
      # Push Docker Image
      ####################################################

      - name: Push Docker Image

        run: |

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      ####################################################
      # Verify Image Exists in ECR
      ####################################################

      - name: Verify Image

        run: |

          aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --image-ids imageTag=${{ github.sha }}

      ####################################################
      # Export Image URI
      ####################################################

      - name: Export Image URI

        id: export-image

        run: |

          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}"

          echo "image=$IMAGE_URI" >> "$GITHUB_OUTPUT"

          echo "Built Image: $IMAGE_URI"

      ####################################################
      # Save Image URI
      ####################################################

      - name: Save Image URI

        run: |

          echo "${{ steps.export-image.outputs.image }}" > image.txt

      ####################################################
      # Upload Image Artifact
      ####################################################

      - name: Upload Image Artifact

        uses: actions/upload-artifact@v4

        with:
          name: docker-image

          path: image.txt

      ####################################################
      # Download Terraform Artifact
      ####################################################

      - name: Download Terraform Source

        uses: actions/download-artifact@v4

        with:
          name: terraform-source

      ####################################################
      # Build Summary
      ####################################################

      - name: Build Summary

        run: |

          echo "========================================="
          echo "Docker Build Completed"
          echo "Repository : $ECR_REPOSITORY"
          echo "Image Tag  : ${{ github.sha }}"
          echo "Region     : $AWS_REGION"
          echo "========================================="

##########################################################
# PART C STARTS BELOW
#########################################################


          ##########################################################
# DOCKER BUILD & PUSH
##########################################################

  docker-build:

    name: Build & Push Docker Image

    needs:
      - terraform-validation
      - terraform-lint

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    outputs:
      image-uri: ${{ steps.export-image.outputs.image }}

    steps:

      ####################################################
      # Checkout Repository
      ####################################################

      - name: Checkout Repository

        uses: actions/checkout@v4

      ####################################################
      # Configure AWS Credentials
      ####################################################

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      ####################################################
      # Login to Amazon ECR
      ####################################################

      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # Show Docker Version
      ####################################################

      - name: Docker Version

        run: docker version

      ####################################################
      # Build Docker Image
      ####################################################

      - name: Build Docker Image

        run: |

          docker build \
            -t $ECR_REPOSITORY:${{ github.sha }} \
            .

      ####################################################
      # Tag Docker Image
      ####################################################

      - name: Tag Docker Image

        run: |

          docker tag \
            $ECR_REPOSITORY:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      ####################################################
      # Push Docker Image
      ####################################################

      - name: Push Docker Image

        run: |

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      ####################################################
      # Verify Image Exists in ECR
      ####################################################

      - name: Verify Image

        run: |

          aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --image-ids imageTag=${{ github.sha }}

      ####################################################
      # Export Image URI
      ####################################################

      - name: Export Image URI

        id: export-image

        run: |

          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}"

          echo "image=$IMAGE_URI" >> "$GITHUB_OUTPUT"

          echo "Built Image: $IMAGE_URI"

      ####################################################
      # Save Image URI
      ####################################################

      - name: Save Image URI

        run: |

          echo "${{ steps.export-image.outputs.image }}" > image.txt

      ####################################################
      # Upload Image Artifact
      ####################################################

      - name: Upload Image Artifact

        uses: actions/upload-artifact@v4

        with:
          name: docker-image

          path: image.txt

      ####################################################
      # Download Terraform Artifact
      ####################################################

      - name: Download Terraform Source

        uses: actions/download-artifact@v4

        with:
          name: terraform-source

      ####################################################
      # Build Summary
      ####################################################

      - name: Build Summary

        run: |

          echo "========================================="
          echo "Docker Build Completed"
          echo "Repository : $ECR_REPOSITORY"
          echo "Image Tag  : ${{ github.sha }}"
          echo "Region     : $AWS_REGION"
          echo "========================================="

##########################################################
# PART C STARTS BELOW
##########################################################
